src/Http/Session.php
tests/Http/Session.handler-exceptions.phpt

I need to throw exception the SessionHandler.
Currently, when you throw an exception from there, the php thinks the session is started (it doesn't care about the exception) and Nette think it's not started, because the `self::$started = TRUE;` wasn't executed.
This creates a buggy state, where you cannot call `$session->start()` again, because it throws `Nette\InvalidStateException("session_start(): session is already started")`
Failing test is provided.

Session: fix handling exceptions thrown from SessionHandlerInterface

---

src/Http/RequestFactory.php
tests/Http/RequestFactory.scriptPath.phpt

This is very annoying on Windows. Either it must give a meaningful exception message, or be case insensitive.
This reverts commit 06cc6f48b73a2ab2a3c902e4d869eeef4aa810ce

RequestFactory: reverted that script path detection is case-sensitive

---

src/Http/Session.php
tests/Http/Session.id.phpt
tests/Http/Session.regenerate-empty-session.phpt

The `nette-browser` is also fetched from `Http\IRequest`, so the `session_name()` should probably be too.
For example I might be writing my own little http server using [react.php](https://github.com/reactphp/http) that accepts requests and processes them through sockets and is started from CLI. This would mean that I have to initialize the `$_COOKIES` variable instead of passing it in a nice OO interface through manually created `Http\Request`.
The fetching of the cookie alone would help a lot. The setting of the cookie to the global variable is a paranoid safety-net, for cases where something depends on the variable existing other than `Nette\Http\Session`. If you have a problem with modifying the global variable, I can remove it. But I'd rather keep it there.

Session: fetch session cookie from Http\IRequest

---

src/Http/Url.php

It was a typo in condition for PHP version checking.
"Else" condition was never been called.
Result of the method should be unchanged after the PR.

Url::getQuery: PHP version condition fixed

---

src/Http/Session.php

Fixes `session_regenerate_id(): Session object destruction failed` which sometimes occures.
See same fix: https://github.com/yiisoft/yii/issues/2376

Fix session_regenerate_id

---

src/Http/Response.php

I've found minor problems. 
Invalid type in phpDoc of two Response's properties.

Response: phpDoc fixes

---

src/Http/IRequest.php

- **feature:** Added PATCH to method constants in `Nette\Http\IRequest` interface. It could be handy when designing REST APIs with Nette framework.
- **issues:** none
- **documentation:** not needed
- **BC break:** no

IRequest: added PATCH method constant

---

src/Http/Session.php

Constant `SID` doesn't detect active session properly and might return `TRUE` for inactive session.
Since PHP 5.4 there is better way to detect: [`session_status()`](http://php.net/manual/es/function.session-status.php)
```php
session_start();
var_dump(defined('SID')); // TRUE
var_dump(session_status() === PHP_SESSION_ACTIVE); // TRUE
session_destroy();
var_dump(defined('SID')); // TRUE
var_dump(session_status() === PHP_SESSION_ACTIVE); // FALSE
```

Use better detection for started session

---

src/Http/RequestFactory.php
tests/Http/RequestFactory.proxy.phpt

- bugfix
- issues - #87 
- documentation - not needed
- BC break - no

RequestFactory: Fixed possible remoteAddr spoofing (issue #87)

---

src/Http/Session.php

Deprecated error was triggered.
$this->started instead of self::$started was used.

Session: used static access to $started

---

src/Http/FileUpload.php
tests/Http/FileUpload.basic.phpt

How do you feel about adding `isEmpty()` shortcut to `FileUpload`
defined as `$this->error === UPLOAD_ERR_NO_FILE`?

Feature: Missing FileUpload::isEmpty()

---

src/Http/RequestFactory.php
tests/Http/RequestFactory.proxy.forwarded.phpt

- bugfix
- issues - #101 
- documentation - not needed
- BC break - yes
BC break if and only if somebody implemented their proxy settings by the actual code. If they went by the documentation or the RFC, they should be fine and this commit actually fixes things.

Conform to the RFC for "forwarded" header

---

src/Http/Session.php

There is a problem that when request fails in specific moment, sessions gets destroyed and the `$nf` variable is then equal to `0`. This allows the session to recover without throwing error.

Make sure __NF in session is array

---

src/Http/UrlScript.php
tests/Http/UrlScript.parse.phpt

To alleviate the pain caused by https://github.com/nette/http/commit/12ac75cf816d21716cf4e0d58ded693e3dae7c63 I suggest adding optional parameter to UrlScript's constructor.

UrlScript: accept option $scriptPath param in constructor

---

src/Http/Response.php

According to [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.1.2) (HTTP/1.1), the first line of a HTTP response must be:
```
The first line of a response message is the status-line, consisting
of the protocol version, a space (SP), the status code, another
space, a possibly empty textual phrase describing the status code,
and ending with CRLF.
status-line = HTTP-version SP status-code SP reason-phrase CRLF
```
When setting a custom code through the setCode method, Nette omits this part:
> another space, a possibly empty textual phrase describing the status code
This is easily fixed by calling the `http_response_code` function that's in PHP.
We bumped into this issue when trying to call our own application with Guzzle which has a strict parsing rules of HTTP responses. [It …

Fixed Http\Response::setCode producing invalid HTTP header

---

composer.json
src/Bridges/HttpDI/HttpExtension.php
tests/Http.DI/HttpExtension.headers.phpt

- bug fix? no   
- new feature? yes
- BC break? no
config:
```neon
http:
policy:
script-src: nonce
img-src: https: 
```
presenter:
```php
function beforeRender()
{
$this->template->nonce = $this->getHttpResponse()->getNonce();
}
```
template:
```latte
<script src="https://www.google-analytics.com/analytics.js" async defer nonce={$nonce}></script>
```
presenter is not changed
```latte
<script src="https://www.google-analytics.com/analytics.js" async defer n:nonce></script>
```

Added support for Content-Security-Policy [WIP]

---

src/Http/RequestFactory.php
tests/Http/RequestFactory.proxy.x-forwarded.phpt

- bug fix
- no BC break
This fixes a warning which happened on our production servers. Generally, ipMatch() function should be able to handle invalid input without a warning.
The cause was an invalid header
`HTTP_X_FORWARDED_FOR: "192.168.5.237,mcd14281.lax,mcd14281.lax, 64.134.222.215, 185.152.66.10, 100.97.10.64"`
which was parsed by RequestFactory and validated against known/allowed proxies.

Hlepers::ipMatch() fixed warning when passed invalid IP address

---

src/Http/Session.php

- bug fix? yes
- new feature? depends
- BC break? no, hopefully
This fixes the issue when new instance of DI container (with session service) is created after session has been manually aborted via `session_abort()` due to database transaction failure.

Session: initialize $started property in constructor

---

src/Http/FileUpload.php

- bug fix? no
- new feature? yes
- BC break? no
According to content types in `Nette\Utils\Image` added `image/webp` to `isImage()` method.

FileUpload: Add Webp to isImage

---

src/Bridges/HttpDI/HttpExtension.php

- new feature
- BC break? no
Avoid processing `frames` config if header `X-Frame-Options` is already set in configuration. If `X-Frame-Options` header is already set, there is unnecessary invocation of `preg_match`, etc. This `frames` key option should not be processed at all in this case.

HttpExtension: X-Frame-Options header

---

src/Http/Url.php
src/Http/UrlImmutable.php
tests/Http/Url.httpScheme.phpt
tests/Http/UrlImmutable.Url.phpt

- bug fix?  yes #158
- BC break? no
Include "empty" hostname (`0`) in the host URL
Fix #158

Include "empty" hostname ('0') in the host URL

---

src/Bridges/HttpDI/SessionExtension.php
src/Http/Session.php

Closes #155 
Should be the only option which is configurable only in session_start.

Session: read_and_close configuration

---

src/Http/FileUpload.php
tests/Http/FileUpload.basic.phpt

- new feature
- BC break? yes
In the case of the name `logo 2020+.pdf` old function return `logo-2020-.pdf`. I think more better behavior is simply `logo-2020.pdf` (without minus before dot separator).
Thanks.

FileUpload::getSanitizedName: Remove redundant minus before dot.

---

src/Http/UrlScript.php

- bug fix: #187 
- BC break? no
`UrlScript` is not work correctly when is extended. The [method `withPath()`](https://github.com/nette/http/blob/v3.0.5/src/Http/UrlScript.php#L53-L58) is calling themself recursive in infinite loop and crash with error:
```
Maximum function nesting level of '256' reached, aborting!
```
The reason is the callback `parent::withPath` in `call_user_func()` function is always called in top of descendants hierarchy context (see more at issue #187).
PR is changing relative reference to parent class to absolute. Here is no able to use only `parent` because method is called in another instance than `$this` (cloned one).
Tests:
- All passed.
- No new one necessary
Resolve #187

ScriptUrl: Fix class extendability (issue #187)

---

src/Http/SessionSection.php

- bug fix #191
- BC break? no
Session section __get() should return reference

SessionSection: __get() returns reference (#191)

---

src/Http/Session.php

- **bug fix**
- BC break? **no**
The condition has been always evaluated to `false` which led to `Warning: session_destroy(): Trying to destroy uninitialized session` instead of `InvalidStateException`.

Session: fixed condition in destroy()

---

src/Http/Request.php
src/Http/RequestFactory.php
tests/Http/RequestFactory.userAndPassword.phpt

- new feature
- BC break? yes
- doc PR: nette/docs#932
Currently is too risky use `Url` object from from `Http\Request` created from global, because it can simply cause to leak user's credentials:
```php
echo $httpRequest->getUrl();
// https://example.com@username:password/index.php
```
The `Url` object already provide method `–>withoutUserInfo()` to remove user credential, but when programer forgot to use that, the credentials can leaks.
This PR ir removing user's credentials from `Url` object and move it to `Http\Request` directly.
It's based on czech discussion at Nette Forum: https://forum.nette.org/cs/33127-http-basic-login-http-url-nette-3-security-issue
I know, it's too naive PR, here is missing any way to notify developer the `Url->getUser()` no more get user from current request. …

Request: Move Basic Auth credential from Url to Request due to prevent leak it

---

src/Http/RequestFactory.php
tests/Http/Request.files.directory.phpt

- new feature
- BC break? no
- doc PR: nette/docs#937
As a follow-up to #207, this adds support for correctly transforming directory uploads into FileUpload objects to RequestFactory.

RequestFactory: support full_path

---

src/Bridges/HttpDI/SessionExtension.php

- bug fix (hopefully fix for https://forum.nette.org/cs/35361-cannot-configure-read-and-close-for-already-started-session)
- BC break? no
Session class throws exception if session is started and option read_and_close is set.
https://github.com/nette/http/blob/0679e7c51a76a2db1da0804b99c83eb3152d84b3/src/Http/Session.php#L401-L404
SessionExtension breaks compatibility with other session implementations (in case they already started the session) by always setting that option (to default value).
https://github.com/nette/http/blob/0679e7c51a76a2db1da0804b99c83eb3152d84b3/src/Bridges/HttpDI/SessionExtension.php#L40

SessionExtension: don't set readAndClose if null

---

src/Http/Session.php

- new feature
- BC break? no
There was an issue #208 - phpredis session driver was raising a notice, when session lock can't be obtained. Nette Session was correctly converting this notice to an exception. The strange was, that even the notice was raised, `session_start` returned `true` (it was phpredis problem).
Now, the new production version of phpredis is out, and the behavior is a little bit different. If a lock can't be obtained, instead of notice, the warning (instead of a notice) is raised and the `session_start` returned correctly `false`.
The problem is, I need to know the reason why the session wasn't started (when redis is death, it's a problem, when session lock can't be obtained, it's probably OK - user is probably doing many parallel requests). …

Session: keep exceptions chain on session_start

---

readme.md
src/Http/IResponse.php

Adds `string` and `DateTimeInterface` back to `setCookie` `$expire` param .
This is a fix for an undocumented (and possibly unwanted) BC break in 3.3.0.
In version 3.2.x and older, this was the type in the docblock.
Also fix the readme which had a wrong param name.
Close #233

Add DateTimeInterface to setCookie $expire param
